{
  "id": "CVE-2022-30877",
  "assigner": "cve@mitre.org",
  "Published": "2022-06-08T16:15:08.363Z",
  "Modified": "2022-06-15T12:33:32.187Z",
  "last-modified": "2022-06-15T12:33:32.187Z",
  "summary": "The keep for python, as distributed on PyPI, included a code-execution backdoor inserted by a third party. The current version, without this backdoor, is 1.2.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 7.5,
  "exploitabilityScore": 10.0,
  "impactScore": 6.4,
  "cvss-vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
  "references": [
    "http://pypi.doubanio.com/simple/request",
    "https://github.com/OrkoHunter/keep/issues/85",
    "https://pypi.org/project/keep"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-94",
  "vulnerable_configuration_cpe_2_2": []
}