{
  "id": "CVE-2018-20989",
  "assigner": "cve@mitre.org",
  "Published": "2019-08-26T16:15:11.483Z",
  "Modified": "2019-08-30T11:18:22.727Z",
  "last-modified": "2019-08-30T11:18:22.727Z",
  "summary": "An issue was discovered in the untrusted crate before 0.6.2 for Rust. Error handling can trigger an integer underflow and panic.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 5.0,
  "exploitabilityScore": 10.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
  "references": [
    "https://rustsec.org/advisories/RUSTSEC-2018-0001.html"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:untrusted_project:untrusted:-:*:*:*:*:*:*:*",
    "cpe:2.3:a:untrusted_project:untrusted:0.5.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:untrusted_project:untrusted:0.6.0:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:untrusted_project:untrusted:-:*:*:*:*:*:*:*",
    "cpe:2.3:a:untrusted_project:untrusted:0.5.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:untrusted_project:untrusted:0.6.0:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "untrusted_project"
  ],
  "products": [
    "untrusted"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:untrusted_project:untrusted"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:untrusted_project:untrusted"
  ],
  "cwe": "CWE-191",
  "vulnerable_configuration_cpe_2_2": []
}