{
  "id": "CVE-2021-36754",
  "assigner": "cve@mitre.org",
  "Published": "2021-07-30T12:15:18.253Z",
  "Modified": "2021-08-07T00:28:09.053Z",
  "last-modified": "2021-08-07T00:28:09.053Z",
  "summary": "PowerDNS Authoritative Server 4.5.0 before 4.5.1 allows anybody to crash the process by sending a specific query (QTYPE 65535) that causes an out-of-bounds exception.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 5.0,
  "exploitabilityScore": 10.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
  "references": [
    "http://www.openwall.com/lists/oss-security/2021/07/26/2",
    "https://doc.powerdns.com/authoritative/security-advisories/index.html",
    "https://doc.powerdns.com/authoritative/security-advisories/powerdns-advisory-2021-01.html"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:-:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:alpha1:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:beta1:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:rc1:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:rc2:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:-:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:alpha1:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:beta1:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:rc1:*:*:*:*:*:*",
    "cpe:2.3:a:powerdns:authoritative_server:4.5.0:rc2:*:*:*:*:*:*"
  ],
  "vendors": [
    "powerdns"
  ],
  "products": [
    "authoritative_server"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:powerdns:authoritative_server"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:powerdns:authoritative_server"
  ],
  "cwe": "CWE-119",
  "vulnerable_configuration_cpe_2_2": []
}