{
  "id": "CVE-2020-4612",
  "assigner": "psirt@us.ibm.com",
  "Published": "2020-09-22T12:15:12.487Z",
  "Modified": "2021-07-21T09:39:23.747Z",
  "last-modified": "2021-07-21T09:39:23.747Z",
  "summary": "IBM Data Risk Manager (iDNA) 2.0.6 could allow an authenticated user to obtain sensitive information using a specially crafted HTTP request. IBM X-Force ID: 184924.",
  "access": {
    "authentication": "SINGLE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "NONE",
    "confidentiality": "PARTIAL",
    "integrity": "NONE"
  },
  "cvss": 4.0,
  "exploitabilityScore": 8.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:S/C:P/I:N/A:N",
  "references": [
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/184924",
    "https://www.ibm.com/support/pages/node/6335281"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "ibm"
  ],
  "products": [
    "data_risk_manager"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:ibm:data_risk_manager"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:ibm:data_risk_manager"
  ],
  "cwe": "NVD-CWE-noinfo",
  "vulnerable_configuration_cpe_2_2": []
}