{
  "id": "CVE-2022-26280",
  "assigner": "cve@mitre.org",
  "Published": "2022-03-28T20:15:09.637Z",
  "Modified": "2022-11-28T18:58:52.717Z",
  "last-modified": "2022-11-28T18:58:52.717Z",
  "summary": "Libarchive v3.6.0 was discovered to contain an out-of-bounds read via the component zipx_lzma_alone_init.",
  "access": {
    "authentication": "NONE",
    "complexity": "MEDIUM",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "PARTIAL",
    "integrity": "NONE"
  },
  "cvss": 5.8,
  "exploitabilityScore": 8.6,
  "impactScore": 4.9,
  "cvss-vector": "AV:N/AC:M/Au:N/C:P/I:N/A:P",
  "references": [
    "https://github.com/libarchive/libarchive/issues/1672",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SBYGJICQ7FKDZ2IIOAH423IHWQ6MNONQ/",
    "https://security.gentoo.org/glsa/202208-26"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-125",
  "vulnerable_configuration_cpe_2_2": []
}