{
  "id": "CVE-2020-4617",
  "assigner": "psirt@us.ibm.com",
  "Published": "2020-09-22T12:15:12.863Z",
  "Modified": "2020-09-22T15:03:18.503Z",
  "last-modified": "2020-09-22T15:03:18.503Z",
  "summary": "IBM Data Risk Manager (iDNA) 2.0.6 is vulnerable to cross-site request forgery which could allow an attacker to execute malicious and unauthorized actions transmitted from a user that the website trusts. IBM X-Force ID: 184930.",
  "access": {
    "authentication": "NONE",
    "complexity": "MEDIUM",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "NONE",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 5.8,
  "exploitabilityScore": 8.6,
  "impactScore": 4.9,
  "cvss-vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N",
  "references": [
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/184930",
    "https://www.ibm.com/support/pages/node/6335281"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "ibm"
  ],
  "products": [
    "data_risk_manager"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:ibm:data_risk_manager"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:ibm:data_risk_manager"
  ],
  "cwe": "CWE-352",
  "vulnerable_configuration_cpe_2_2": []
}