{
  "id": "CVE-2013-2013",
  "assigner": "secalert@redhat.com",
  "Published": "2013-10-01T18:55:33.623Z",
  "Modified": "2017-09-18T23:36:15.107Z",
  "last-modified": "2017-09-18T23:36:15.107Z",
  "summary": "The user-password-update command in python-keystoneclient before 0.2.4 accepts the new password in the --password argument, which allows local users to obtain sensitive information by listing the process.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "LOCAL"
  },
  "impact": {
    "availability": "NONE",
    "confidentiality": "PARTIAL",
    "integrity": "NONE"
  },
  "cvss": 2.1,
  "exploitabilityScore": 3.9,
  "impactScore": 2.9,
  "cvss-vector": "AV:L/AC:L/Au:N/C:P/I:N/A:N",
  "references": [
    "http://www.openwall.com/lists/oss-security/2013/05/23/4",
    "https://bugs.launchpad.net/python-keystoneclient/+bug/938315",
    "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A16937"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:openstack:python-keystoneclient:0.2.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:openstack:python-keystoneclient:0.2.3:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:openstack:python-keystoneclient:0.2.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:openstack:python-keystoneclient:0.2.3:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "openstack"
  ],
  "products": [
    "python-keystoneclient"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:openstack:python-keystoneclient"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:openstack:python-keystoneclient"
  ],
  "cwe": "CWE-200",
  "vulnerable_configuration_cpe_2_2": []
}