{
  "id": "CVE-2021-25901",
  "assigner": "cve@mitre.org",
  "Published": "2021-01-26T17:16:22.333Z",
  "Modified": "2021-02-02T18:51:11.993Z",
  "last-modified": "2021-02-02T18:51:11.993Z",
  "summary": "An issue was discovered in the lazy-init crate through 2021-01-17 for Rust. Lazy lacks a Send bound, leading to a data race.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 5.0,
  "exploitabilityScore": 10.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
  "references": [
    "https://rustsec.org/advisories/RUSTSEC-2021-0004.html"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:lazy-init_project:lazy-init:0.1.0:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.1.1:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.2.0:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.3.0:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.4.0:*:*:*:*:rust:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:lazy-init_project:lazy-init:0.1.0:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.1.1:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.2.0:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.3.0:*:*:*:*:rust:*:*",
    "cpe:2.3:a:lazy-init_project:lazy-init:0.4.0:*:*:*:*:rust:*:*"
  ],
  "vendors": [
    "lazy-init_project"
  ],
  "products": [
    "lazy-init"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:lazy-init_project:lazy-init"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:lazy-init_project:lazy-init"
  ],
  "cwe": "NVD-CWE-noinfo",
  "vulnerable_configuration_cpe_2_2": []
}